system:
    default:
        fielddefinition_edit_templates:
            - { template: "@ezdesign/matrix_fieldtype/field_types.html.twig", priority: 1 }

        field_templates:
            - { template: '@ezdesign/matrix_fieldtype/content_fields.html.twig', priority: 1 }

    admin_group:
        admin_ui_forms:
            content_edit_form_templates:
                - { template: '@ezdesign/matrix_fieldtype/content_edit_form_fields.html.twig', priority: 1 }
