name: Frontend build

on:
    push:
        paths:
            - "**.js"
        branches:
            - $default-branch
            - '[0-9]+.[0-9]+'
    pull_request:
        paths:
            - "**.js"

jobs:
    frontend-test:
        name: Frontend build test
        runs-on: "ubuntu-20.04"
        timeout-minutes: 5

        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'
            -   run: yarn install
            -   run: yarn test
