services:
    ezplatform.matrix.fieldtype.javascripts:
        parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
        autowire: true
        autoconfigure: false
        public: false
        arguments:
            $template: '@@ezdesign/matrix_fieldtype/javascripts.component.html.twig'
        tags:
            - { name: ezplatform.admin_ui.component, group: 'script-body' }
